### ISSUE TITLE
Missing BBCode tags in the Fuuka API

### ISSUE THREAD

**Issue by ccd0** [bstats/b-stats#1]
Currently the formatting tags on /qst/ don't show up in archived threads
https://archive.b-stats.org/qst/thread/40963
and they aren't parsed back into `[tag]` format in the JSON API, but are sent as the original HTML.
https://archive.b-stats.org/_/api/chan/post/?board=qst&num=40963

**Comment by bstats** [comment]
Unlike Asagi/FoolFuuka, I store the comment's full HTML in the database, in order to preserve formatting in mod posts, etc. The FoolFuuka adapter is meant to revert the HTML back to BBcode, but it is currently... less than perfect in that regard. If only 4chan provided the BBcode in their API! I'll see what I can do to fix this.

**Comment by bstats** [comment]
@ccd0 is there any place that lists all the available formatting tags? I only know of [code] and [spoiler]

**Comment by r3c0d3x** [comment]
Not him, but if he doesn't have a list, I suppose you can make a list from checking the stickies on each board.

**Comment by ccd0** [comment]
> is there any place that lists all the available formatting tags? I only know of [code] and [spoiler]

I don't know of any complete list.
https://a.4cdn.org/boards.json
now documents which boards have which tags, although the /qst/ ones are not included yet, and I don't think it's documented anywhere that, for example `math_tags` means that /sci/ has both `[math]` and `[eqn]`.

Additionally you can see what's currently handled by Asagi at:
https://github.com/eksopl/asagi/blob/e0afce64c925360f2ddd9eea83d4b8f2063cd49c/src/main/java/net/easymodo/asagi/YotsubaAbstract.java#L82-L129

The tags I'm aware of are
- `[spoiiler]`
- `[code]` (/g/)
- `[math]` and `[eqn]` (/sci/)
- `[sjis]` (/jp/)
- `[b]`, `[i]`, `[red]`, `[green]`, and `[blue]` (/qst/)

Some other stuff that can show up in comments is
- EXIF data (/p/)
- dice rolls (/tg/ and /qst/)
- fortunes (/s4s/)
- (USER WAS BANNED FOR THIS POST)

plus arbitrary HTML that mods can use if they want (stickies often have bold text or large fonts).

**Comment by bstats** [comment]
Yikes, I did not realize Asagi was using regex to strip all the HTML out!

A quick look at the JSON for /sci/ shows that 4chan leaves [math] and [eqn] as the plain bbcode.

**Comment by bstats** [comment]
Okay, that's everything now. Dice rolls are already converted to [b] since they're `<strong>` tags, so I think we're all set here.
