### ISSUE TITLE
Your archive sucks 

### ISSUE THREAD

**Issue by theanimedelusion** [bstats/b-stats#15]
Don't you realize how broken it is? 
Every single fucking link, broken 

I assume you use 4chan X, yes? 

https://boards.4chan.org/lgbt/archive

go through, click any thread, click the arrow and click "archive" 
Absolutely nothing works 

![image](https://user-images.githubusercontent.com/18670258/42122141-14070dd4-7bf2-11e8-81bc-3198bd9b1c79.png)
click that 

every single thread gets this 
![image](https://user-images.githubusercontent.com/18670258/42122147-2562afd4-7bf2-11e8-885d-b155ce92e5a1.png)

it's clear your archive is doing something, why are none of these working? And can you please add search on non /b/ boards please thanks

**Comment by bstats** [comment]
chink moot killed my archiver's (and others') ability to save posts, sux 2 suck
